input {
  tcp {
    port => 5000               # 👈 coincide con LOGSTASH_DESTINATION
    codec => json_lines        # 👈 los logs vienen en JSON (LogstashEncoder)
  }
}

filter {
  # Puedes enriquecer logs si quieres
  mutate {
    add_field => {
      "environment" => "docker-local"
      "app_source"  => "%{[service]}"   # Logback ya pone "service"
    }
  }
}

output {
  stdout { codec => rubydebug }   # 👈 logs debug en consola (útil para pruebas)

  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "logs-%{+YYYY.MM.dd}"     # 👈 crea índice diario
    ilm_enabled => false               # evita que ELK intente policies sin definir
  }
}
