receivers:
  otlp:
    protocols:
      grpc:       # Puerto 4317
      http:       # Puerto 4318

exporters:
  logging:
    loglevel: debug

  prometheus:
    endpoint: "0.0.0.0:9464"

  # 👇 Exportador hacia Tempo
  otlp/tempo:
    endpoint: tempo:4317   # 👈 el servicio "tempo" definido en docker-compose
    tls:
      insecure: true

  # Exportador OTLP vía HTTP → Elastic APM Server
  otlphttp:
    endpoint: "http://apm-server:8200"
    tls:
      insecure: true
processors:
  batch:
    timeout: 10s
    send_batch_size: 512
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, otlp/tempo]   # 👈 ahora sí está definido
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, prometheus, otlphttp]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, otlphttp]
